"""The action list wl.works polls for, in `HealthResponse.actions`. Design spec section 3.

wl.works renders each published action as a button any lab member can press. Its Plan 10
section 4.1 states the rule as the protocol's most prominent line: *"Publishing an action
makes it available to every member of the lab. There is no permission model on the app side.
If an action should not be triggerable by anyone who can log in, do not publish it."* A button
that queues work no computed stage will pick up for six months is a button that teaches people
to distrust the surface — so this module publishes an action for a domain only once something
in `daemon._computed_tables()` actually belongs to it. Today nothing does, so `available_actions`
returns `[]`, and that is the deliverable, not a placeholder for one.

**This is a mapping, not a discovery.** `daemon._computed_tables()` is not introspection over
a schema, a dependency graph, or `populate()`'s own key source — its own docstring says
plainly: *"Empty in 1c-1: nothing computes yet. The ordering lives here so that 1c-4's timebase
and coverage stages, and Phase 2's sorting, extend one list rather than inventing their own
traversal."* It is a hardcoded list later phases append to (read that function before this one).
`_TABLE_DOMAINS` below is the same kind of thing: a hardcoded, currently-empty mapping from a
computed table's `__name__` to one of the five section 11.4 domains, extended by hand in the
same commit that adds the table to `_computed_tables()`. `_stage_domains` only looks entries up
in it — it does not inspect a table's columns, foreign keys, or module to guess which domain it
belongs to.

That still buys the property the design wants: the day a table and its `_TABLE_DOMAINS` entry
both land, its action appears here with no other change in this module and none in wl.works —
which is what `HealthResponse`'s own docstring ("the host publishes its own action list") was
written to buy. It is bought by two hardcoded lists being extended together, not by either one
being discovered.
"""

from __future__ import annotations

from wl_preproc.contracts.protocol import Action
from wl_preproc.schema import DEFAULT_PREFIX

# The five section 11.4 dispatch domains, and the label wl.works renders on each one's button.
# All five are hardcoded here even though `_stage_domains` can today report that none of them
# have a computed stage behind them — the *labels* are known now, and hardcoding them here is
# what keeps a stage's later arrival a change to `_TABLE_DOMAINS` alone rather than to this
# dict too.
#
# `behaviour`, `neural` and `export` are section 11.4's own domain names, taken verbatim from
# its table's Domain column. Rows 27 and 29 are unnamed there — that column reads "--" for
# both — so `atlas` and `calibration` are this module's own choice of identifier, not
# section 11.4's. They are not invented from nothing, though: this repo's parent design spec
# (2026-08-12-wl-preproc-design.md) section 12.1's roadmap table already uses "27b atlas
# registration, 29b calibration" as shorthand for exactly these two rows, and that shorthand is
# where these two strings come from. Whichever later task wires 27b/29b request dispatch
# (section 11.4's own scope, not this one's) must either match these two strings or update this
# dict, since nothing else ties them together today.
#
# Every label below is manually transcribed from its row's own "What this host runs" text in
# that table -- the lead clause describing what the stage does, stopping before the trailing
# operational aside (a GitHub SHA, an output directory size) that reads as a footnote rather
# than caption material -- with markdown backticks dropped since this renders as literal button
# text, not markdown. This is a description of what was done, NOT a mechanical rule a sixth
# label could be generated by: the delimiter marking where each lead clause ends differs per
# row (an em dash for `neural`, a semicolon for `atlas` and `calibration`, no delimiter at all
# for `export`), and `calibration`'s own row has an earlier, unrelated `.` inside the code span
# `` `.spectrashop` `` that a literal first-`.`-scan would hit before the intended semicolon.
# Transcribe the next one by hand, the same way, rather than trusting a "first `.`/`--`/`;`"
# scan to reproduce it.
DOMAIN_LABELS: dict[str, str] = {
    "behaviour": "Per-task behavioural analysis",
    "neural": "Spike sorting",
    "export": "Trim-and-export an NWB to a block subset for DANDI deposit",
    "atlas": "@animal_warper atlas registration",
    "calibration": "Stimulus calibration from a .spectrashop measurement",
}

# Maps a `daemon._computed_tables()` entry's `__name__` to one of the five `DOMAIN_LABELS`
# keys. Empty today because `_computed_tables()` is empty today (see its own docstring) --
# there is nothing yet to map. A future stage lands by adding one line here, in the same
# commit that adds the table itself to `_computed_tables()`.
_TABLE_DOMAINS: dict[str, str] = {}


def _stage_domains(prefix: str = DEFAULT_PREFIX) -> set[str]:
    """Which of the five `DOMAIN_LABELS` keys have a computed stage behind them right now.

    Maps `daemon._computed_tables()` through `_TABLE_DOMAINS` and returns the domains that
    matched — never a discovery over schema contents, dependencies, or naming convention (see
    this module's own docstring and `_computed_tables()`'s for why). A table present in
    `_computed_tables()` with no matching `_TABLE_DOMAINS` entry is silently excluded rather
    than raising: this module's whole stance is that an action which should exist but does not
    appear is the safe failure, while an action appearing before its domain is ready is the one
    section 3 exists to prevent — so a bookkeeping gap here must fail toward "nothing
    published," not crash `/health` for every caller over a missing dict entry.

    `daemon._computed_tables` is imported here, function-local, rather than bound at module
    load — the same reason `health.py`'s `build_health` reaches `gather_readings` the same way:
    a module-level `from wl_preproc.daemon import _computed_tables` would bind its own name at
    THIS module's import time and never observe a `monkeypatch.setattr("wl_preproc.daemon.
    _computed_tables", ...)` applied to the source module afterward, which is exactly the style
    `tests/schema/test_daemon.py` already uses against `daemon` directly.

    `prefix` is accepted for interface symmetry with `available_actions` (itself following
    `daemon.reap_stale_jobs` / `count_stale_jobs`'s own documented precedent) but not read:
    `_computed_tables()` takes no prefix itself, since this project runs one schema prefix per
    process.
    """
    from wl_preproc.daemon import _computed_tables

    return {
        _TABLE_DOMAINS[table.__name__]
        for table in _computed_tables()
        if table.__name__ in _TABLE_DOMAINS
    }


def available_actions(prefix: str = DEFAULT_PREFIX) -> list[Action]:
    """The actions `build_health` publishes in `HealthResponse.actions`.

    One `Action` per domain `_stage_domains` reports as having a computed stage behind it --
    today, none, since `daemon._computed_tables()` is empty. Sorted alphabetically by domain
    name for a deterministic response: `_stage_domains` returns a `set`, which carries no
    order of its own, and wl.works polls this repeatedly, so two calls against the same
    underlying state must render identical JSON. Unlike `health.py`'s readings, actions carry
    no `featured`-style priority to sort by instead — wl.works renders every published action,
    not just one — so alphabetical is the simplest order available without inventing one.
    """
    domains = _stage_domains(prefix=prefix)
    return [Action(name=domain, label=DOMAIN_LABELS[domain]) for domain in sorted(domains)]
